version: '3.7'

services: 
  api-minimal:
    image: api-minimal
    container_name: api-minimal
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      START_WITHOUT_ENVOY: "true"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://*:8080"
      